package Helper

var API_KEY_VALUE = "USER-LOGIN-API"
var UNAUTHORIZED = "UNAUTHORIZED"
var NOT_FOUND = "DATA NOT FOUND"
var FAIL_VALIDATION = "REQUEST DOES NOT PASS VALIDATION"
var BAD_REQUEST = "BAD REQUEST"
var NO_TOKEN = "NO-TOKEN"
